export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL';
export const ALL_USERS_LOADED = 'ALL_USERS_LOADED';
export const LOAD_MORE_USERS = 'LOAD_MORE_USERS';

export const LOAD_FOLLOWERS = 'LOAD_FOLLOWERS';
export const LOAD_FOLLOWERS_SUCCESS = 'LOAD_FOLLOWERS_SUCCESS';
export const LOAD_FOLLOWERS_FAIL = 'LOAD_FOLLOWERS_FAIL';
export const RESET_FOLLOWERS = 'RESET_FOLLOWERS';
export const ALL_FOLLOWERS_LOADED = 'ALL_FOLLOWERS_LOADED';
export const LOAD_MORE_FOLLOWERS = 'LOAD_MORE_FOLLOWERS';
